print ("CV")
print ("Nume Prenume : Bufteac Ecaterina")
print ("Data si locul nasterii: 3o.03.2005, Balti")
print ("Domiciliu: Cartierul  Dacia , strada conev 2")
print ("Studii: 2011-prezent IPLT ‘’M.E’’ ; 2017-prezent SAP(Scoala artelor plastice )")
print ("Performante , rezultate deosebite in activitatea scolara :Olimpiada la l.franceza , diploma de participare la competitii")
print ("Cunoasterea limbilor : Limba franceza – nivelul B2  ,Limba engleza  - nivelul A2 ,Limba germana - incepator ")
print ("Interese (sport, pictura) Practic boxul – 3ani        Pictura (frecventez Scoala artelor plastice) ")
print ("Caracteristici : Sociabila , creativa  , spirit de echipa , responsabila  ")
print ("  Obiective profesionale : Universitatea de medicina  ")